FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 8001
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:8001", "app:app"]
